name: DEPRECATED select-project-token (No-Op)
description: 'Deprecated action retained only for historical reference – performs no work.'

outputs:
  token:
    description: 'Deprecated – always empty.'

runs:
  using: composite
  steps:
    - run: echo 'select-project-token action deprecated; no token selection performed.'
      shell: bash
