name: Node Workspace Setup
description: >-
  Sets up a Node.js monorepo workspace: installs the specified Node version, enables
  Corepack (npm@10), installs all npm workspaces (using npm ci), and optionally builds
  the shared package used across backend/frontend.

inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: '20'
  build-shared:
    description: Whether to build the shared workspace package
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Node ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: |
          package-lock.json
          backend/package.json
          frontend/package.json
          shared/package.json

    - name: Enable Corepack (npm@10)
      shell: bash
      run: corepack enable

    - name: Install dependencies (workspaces + root)
      shell: bash
      run: npm ci --workspaces --include-workspace-root

    - name: Build shared library
      if: ${{ inputs.build-shared == 'true' }}
      shell: bash
      run: npm run build -w shared
