name: Accessibility Scan
# Explicit least-privilege permissions:
# - contents: read -> required for actions/checkout to read repository content
# - actions: write -> required for uploading artifacts (axe reports) and enabling cache features used by setup-node
permissions:
    contents: read
    actions: write

on:
    pull_request:
        paths:
            - 'frontend/**'
            - '.github/workflows/a11y.yml'
            - 'docs/ux/**'
    push:
        branches: [main]
        paths:
            - 'frontend/**'
            - '.github/workflows/a11y.yml'

jobs:
    axe:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
                  cache-dependency-path: |
                      package-lock.json
                      backend/package.json
                      frontend/package.json
                      frontend/api/package.json
                      shared/package.json

            - name: Enable Corepack (npm@10)
              run: corepack enable

            - name: Install workspaces (ci)
              run: npm ci --workspaces

            - name: Build shared + frontend (produce types then assets)
              run: |
                  npm run build -w shared
                  npm run build -w frontend
              # Rationale: shared must emit declaration files before any workspace that (directly or indirectly)
              # compiles TypeScript against its types. Building shared first avoids TS6305 errors if another
              # workspace build is introduced here later (e.g., API) or if the frontend tooling ever relies on
              # the emitted .d.ts instead of source path mapping.

            - name: Run accessibility scan (axe)
              run: npm run a11y

            - name: Upload axe report artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: axe-report
                  path: frontend/axe-report
                  if-no-files-found: ignore
