name: DEPRECATED Auto Update Issue Status (No-Op)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'auto-update-issue-status-on-pr workflow deprecated; no actions performed.'
