name: DEPRECATED Calculate Schedule Variance (No-Op)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'calculate-variance workflow deprecated; no actions performed.'
