name: Monorepo Validation

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch: {}

permissions:
    contents: read
    pull-requests: read

concurrency:
    group: validation-${{ github.ref }}
    cancel-in-progress: true

env:
    NODE_VERSION: '20'

jobs:
    setup-matrix:
        name: Determine Changed Areas
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - id: changed
              uses: dorny/paths-filter@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  filters: |
                      a11y:
                        - 'frontend/**'
                        - 'docs/ux/**'

    lint-typecheck:
        name: Lint & Typecheck
        runs-on: ubuntu-latest
        needs: setup-matrix
        steps:
            - uses: actions/checkout@v4
            - name: Node workspace setup
              uses: ./.github/actions/node-workspace-setup
            - name: Lint
              run: npm run lint
            - name: Typecheck (composite)
              run: npm run typecheck
            - name: Lint summary
              if: always()
              run: echo 'Lint & Typecheck complete' >> $GITHUB_STEP_SUMMARY

    tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: lint-typecheck
        steps:
            - uses: actions/checkout@v4
            - name: Node workspace setup
              uses: ./.github/actions/node-workspace-setup
            - name: Build (composite)
              run: npm run build
            - name: Run tests
              run: npm test
            - name: Coverage Report (text)
              run: npm run coverage || echo 'Coverage step failed (non-blocking).'
            - name: Upload coverage artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: coverage
                  path: coverage
                  if-no-files-found: ignore

    accessibility:
        name: Accessibility (axe)
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        needs: [lint-typecheck]
        steps:
            - uses: actions/checkout@v4
            - name: Node workspace setup
              uses: ./.github/actions/node-workspace-setup
            - name: Build shared + frontend (for production scan context)
              run: |
                  npm run build -w shared
                  npm run build -w frontend
              # Ensures shared declarations exist before any other workspace compiles or tooling inspects types.
            - name: Axe scan (dev server)
              run: npm run a11y
            - name: Upload axe report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: axe-report
                  path: frontend/axe-report
                  if-no-files-found: ignore

    summary:
        name: Summary
        runs-on: ubuntu-latest
        needs: [lint-typecheck, tests, accessibility]
        steps:
            - name: Output Summary
              run: |
                  echo '## Monorepo Validation Summary' >> $GITHUB_STEP_SUMMARY
                  echo '* Lint & Typecheck: ${{ needs.lint-typecheck.result }}' >> $GITHUB_STEP_SUMMARY
                  echo '* Tests: ${{ needs.tests.result }}' >> $GITHUB_STEP_SUMMARY
                  echo '* Accessibility: ${{ needs.accessibility.result }}' >> $GITHUB_STEP_SUMMARY
