name: DEPRECATED DI Suitability Analysis (No-Op)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'di-suitability workflow deprecated; no actions performed.'
