name: DEPRECATED Roadmap Scheduler (No-Op)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'roadmap-scheduler workflow deprecated; no actions performed.'
