name: Validate TypeScript

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "package.json"
      - "frontend/**"
      - "backend/**"
  push:
    branches: [main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "package.json"
      - "frontend/**"
      - "backend/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: validate-typecheck-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"

jobs:
  typecheck:
    name: TypeScript Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install workspaces
        run: npm install --workspaces

      - name: Typecheck all packages
        run: npm run typecheck

      - name: Summary
        if: always()
        run: |
          echo 'Typecheck workflow completed.' >> $GITHUB_STEP_SUMMARY
          echo 'Root script: npm run typecheck' >> $GITHUB_STEP_SUMMARY
          echo 'Workspaces covered: frontend, frontend/api, backend' >> $GITHUB_STEP_SUMMARY
